import { open, stat as statPath } from "node:fs/promises";
import { isAbsolute } from "node:path";
import { parentPort } from "node:worker_threads";
import type {
    DesktopFileFingerprint,
    HashWorkerFailure,
    HashWorkerJob,
    HashWorkerRequest,
    HashWorkerResponse,
} from "./hash-worker-protocol";
import type { WasmModule } from "./push";

// @ts-ignore generated by scripts/build-wasm.sh
import initSimdWasm, * as SimdWasmExports from "../wasm/sync_core_simd";
// @ts-ignore loaded as an inline Uint8Array by esbuild
import simdWasmBytes from "../wasm/sync_core_simd_bg.wasm";

const port = parentPort;
if (!port) throw new Error("hash worker requires a worker_threads parent port");
const workerPort = port as NonNullable<typeof parentPort>;

const cancelled = new Set<string>();
const acceptedJobs = new Set<string>();
const now = (): number => globalThis.performance?.now?.() ?? Date.now();

class WorkerTaskError extends Error {
    constructor(
        readonly code: HashWorkerFailure["code"],
        message: string,
    ) {
        super(message);
        this.name = "WorkerTaskError";
    }
}

function fingerprint(
    stats: Awaited<ReturnType<typeof statPath>>,
): DesktopFileFingerprint {
    return {
        size: Number(stats.size),
        mtime: Number(stats.mtimeMs),
        ctime: Number(stats.ctimeMs),
        device: Number(stats.dev),
        inode: Number(stats.ino),
    };
}

function mtimeMatches(left: number, right: number): boolean {
    return Math.abs(left - right) <= 1;
}

function expectedMatches(job: HashWorkerJob, actual: DesktopFileFingerprint): boolean {
    return actual.size === job.expected_size &&
        mtimeMatches(actual.mtime, job.expected_mtime);
}

function unchanged(
    before: DesktopFileFingerprint,
    after: DesktopFileFingerprint,
): boolean {
    return before.size === after.size &&
        mtimeMatches(before.mtime, after.mtime) &&
        mtimeMatches(before.ctime, after.ctime) &&
        before.device === after.device &&
        before.inode === after.inode;
}

function assertJob(job: HashWorkerJob): void {
    if (
        typeof job.job_id !== "string" || job.job_id.length === 0 || job.job_id.length > 128 ||
        typeof job.absolute_path !== "string" || !isAbsolute(job.absolute_path) ||
        job.absolute_path.includes("\0") ||
        !Number.isSafeInteger(job.expected_size) || job.expected_size < 0 ||
        !Number.isFinite(job.expected_mtime) || job.expected_mtime < 0 ||
        (job.mode !== "hash" && job.mode !== "manifest") ||
        !Number.isInteger(job.feed_bytes) ||
        job.feed_bytes < 64 * 1024 || job.feed_bytes > 1024 * 1024
    ) {
        throw new WorkerTaskError("INVALID_JOB", "invalid hash worker job metadata");
    }
}

function assertNotCancelled(jobId: string): void {
    if (cancelled.has(jobId)) {
        throw new WorkerTaskError("CANCELLED", "hash worker job cancelled");
    }
}

function serializeFailure(jobId: string, error: unknown): HashWorkerFailure {
    if (error instanceof WorkerTaskError) {
        return { type: "error", job_id: jobId, code: error.code, message: error.message };
    }
    const code = (error as NodeJS.ErrnoException | undefined)?.code;
    if (code === "ENOENT" || code === "ESTALE") {
        return {
            type: "error",
            job_id: jobId,
            code: "FILE_DRIFT",
            message: "file disappeared or changed while hashing",
        };
    }
    if (typeof code === "string") {
        return {
            type: "error",
            job_id: jobId,
            code: "IO",
            message: `hash worker I/O failed (${code})`,
        };
    }
    return {
        type: "error",
        job_id: jobId,
        code: "INTERNAL",
        message: "hash worker failed",
    };
}

async function execute(job: HashWorkerJob, wasm: WasmModule): Promise<HashWorkerResponse> {
    assertJob(job);
    assertNotCancelled(job.job_id);

    const handle = await open(job.absolute_path, "r");
    let processor: InstanceType<WasmModule["Hasher"]> | InstanceType<WasmModule["WasmChunker"]> | null = null;
    try {
        const before = fingerprint(await handle.stat());
        if (!expectedMatches(job, before)) {
            throw new WorkerTaskError("FILE_DRIFT", "file metadata changed before hashing");
        }

        processor = job.mode === "hash" ? new wasm.Hasher() : new wasm.WasmChunker();
        const buffer = Buffer.allocUnsafe(job.feed_bytes);
        let offset = 0;
        let readMs = 0;
        let hashMs = 0;
        while (offset < before.size) {
            assertNotCancelled(job.job_id);
            const readStarted = now();
            const { bytesRead } = await handle.read(
                buffer,
                0,
                Math.min(buffer.length, before.size - offset),
                offset,
            );
            readMs += Math.max(0, now() - readStarted);
            if (bytesRead === 0) {
                throw new WorkerTaskError("FILE_DRIFT", "file ended while hashing");
            }
            const hashStarted = now();
            processor.update(new Uint8Array(buffer.buffer, buffer.byteOffset, bytesRead));
            hashMs += Math.max(0, now() - hashStarted);
            offset += bytesRead;
        }
        assertNotCancelled(job.job_id);

        const finalizeStarted = now();
        const value = job.mode === "hash"
            ? (processor as InstanceType<WasmModule["Hasher"]>).finalize()
            : (processor as InstanceType<WasmModule["WasmChunker"]>).finish();
        hashMs += Math.max(0, now() - finalizeStarted);

        // Stat the pathname, not only the open handle: atomic replacement can
        // leave the handle stable while the vault path points at another inode.
        const after = fingerprint(await statPath(job.absolute_path));
        if (!unchanged(before, after) || !expectedMatches(job, after)) {
            throw new WorkerTaskError("FILE_DRIFT", "file metadata changed while hashing");
        }

        if (job.mode === "hash") {
            return {
                type: "result",
                job_id: job.job_id,
                mode: "hash",
                hash: value as string,
                size: after.size,
                mtime: after.mtime,
                fingerprint: after,
                read_ms: readMs,
                hash_ms: hashMs,
            };
        }
        return {
            type: "result",
            job_id: job.job_id,
            mode: "manifest",
            manifest: value as any,
            size: after.size,
            mtime: after.mtime,
            fingerprint: after,
            read_ms: readMs,
            hash_ms: hashMs,
        };
    } finally {
        processor?.free();
        await handle.close();
    }
}

async function main(): Promise<void> {
    const bytes = simdWasmBytes as unknown as Uint8Array;
    if (!WebAssembly.validate(bytes as BufferSource)) {
        throw new Error("SIMD unavailable");
    }
    await initSimdWasm({ module_or_path: bytes });
    const wasm = SimdWasmExports as unknown as WasmModule;
    workerPort.postMessage({ type: "ready", wasm_mode: "simd" } satisfies HashWorkerResponse);

    let chain = Promise.resolve();
    workerPort.on("message", (message: HashWorkerRequest) => {
        if (message?.type === "cancel") {
            if (typeof message.job_id === "string" && acceptedJobs.has(message.job_id)) {
                cancelled.add(message.job_id);
            }
            return;
        }
        if (message?.type !== "job") return;
        acceptedJobs.add(message.job_id);
        chain = chain.then(async () => {
            try {
                workerPort.postMessage(await execute(message, wasm));
            } catch (error) {
                workerPort.postMessage(serializeFailure(message.job_id, error));
            } finally {
                cancelled.delete(message.job_id);
                acceptedJobs.delete(message.job_id);
            }
        });
    });
}

void main().catch(() => {
    workerPort.postMessage({ type: "fatal", message: "hash worker WASM initialization failed" } satisfies HashWorkerResponse);
});
