// automatically generated by the FlatBuffers compiler, do not modify

// @generated

use core::cmp::Ordering;
use core::mem;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod sync_chunk {

    use core::cmp::Ordering;
    use core::mem;

    extern crate flatbuffers;
    use self::flatbuffers::{EndianScalar, Follow};

    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MIN_NODE_TYPE: u8 = 0;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    pub const ENUM_MAX_NODE_TYPE: u8 = 3;
    #[deprecated(
        since = "2.0.0",
        note = "Use associated constants instead. This will no longer be generated in 2021."
    )]
    #[allow(non_camel_case_types)]
    pub const ENUM_VALUES_NODE_TYPE: [NodeType; 4] = [
        NodeType::NONE,
        NodeType::LeafChunk,
        NodeType::InternalNode,
        NodeType::RootNode,
    ];

    #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
    #[repr(transparent)]
    pub struct NodeType(pub u8);
    #[allow(non_upper_case_globals)]
    impl NodeType {
        pub const NONE: Self = Self(0);
        pub const LeafChunk: Self = Self(1);
        pub const InternalNode: Self = Self(2);
        pub const RootNode: Self = Self(3);

        pub const ENUM_MIN: u8 = 0;
        pub const ENUM_MAX: u8 = 3;
        pub const ENUM_VALUES: &'static [Self] = &[
            Self::NONE,
            Self::LeafChunk,
            Self::InternalNode,
            Self::RootNode,
        ];
        /// Returns the variant's name or "" if unknown.
        pub fn variant_name(self) -> Option<&'static str> {
            match self {
                Self::NONE => Some("NONE"),
                Self::LeafChunk => Some("LeafChunk"),
                Self::InternalNode => Some("InternalNode"),
                Self::RootNode => Some("RootNode"),
                _ => None,
            }
        }
    }
    impl core::fmt::Debug for NodeType {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            if let Some(name) = self.variant_name() {
                f.write_str(name)
            } else {
                f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
            }
        }
    }
    impl<'a> flatbuffers::Follow<'a> for NodeType {
        type Inner = Self;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
            Self(b)
        }
    }

    impl flatbuffers::Push for NodeType {
        type Output = NodeType;
        #[inline]
        unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
            flatbuffers::emplace_scalar::<u8>(dst, self.0);
        }
    }

    impl flatbuffers::EndianScalar for NodeType {
        type Scalar = u8;
        #[inline]
        fn to_little_endian(self) -> u8 {
            self.0.to_le()
        }
        #[inline]
        #[allow(clippy::wrong_self_convention)]
        fn from_little_endian(v: u8) -> Self {
            let b = u8::from_le(v);
            Self(b)
        }
    }

    impl<'a> flatbuffers::Verifiable for NodeType {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            u8::run_verifier(v, pos)
        }
    }

    impl flatbuffers::SimpleToVerifyInSlice for NodeType {}
    pub struct NodeTypeUnionTableOffset {}

    pub enum FileEntryOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct FileEntry<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for FileEntry<'a> {
        type Inner = FileEntry<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: flatbuffers::Table::new(buf, loc),
            }
        }
    }

    impl<'a> FileEntry<'a> {
        pub const VT_PATH: flatbuffers::VOffsetT = 4;
        pub const VT_HASH: flatbuffers::VOffsetT = 6;
        pub const VT_MTIME_MS: flatbuffers::VOffsetT = 8;
        pub const VT_SIZE_BYTES: flatbuffers::VOffsetT = 10;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            FileEntry { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args FileEntryArgs<'args>,
        ) -> flatbuffers::WIPOffset<FileEntry<'bldr>> {
            let mut builder = FileEntryBuilder::new(_fbb);
            builder.add_size_bytes(args.size_bytes);
            builder.add_mtime_ms(args.mtime_ms);
            if let Some(x) = args.hash {
                builder.add_hash(x);
            }
            if let Some(x) = args.path {
                builder.add_path(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn path(&self) -> &'a str {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(FileEntry::VT_PATH, None)
                    .unwrap()
            }
        }
        #[inline]
        pub fn hash(&self) -> flatbuffers::Vector<'a, u8> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                        FileEntry::VT_HASH,
                        None,
                    )
                    .unwrap()
            }
        }
        #[inline]
        pub fn mtime_ms(&self) -> u64 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<u64>(FileEntry::VT_MTIME_MS, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn size_bytes(&self) -> u64 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<u64>(FileEntry::VT_SIZE_BYTES, Some(0))
                    .unwrap()
            }
        }
    }

    impl flatbuffers::Verifiable for FileEntry<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>("path", Self::VT_PATH, true)?
                .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                    "hash",
                    Self::VT_HASH,
                    true,
                )?
                .visit_field::<u64>("mtime_ms", Self::VT_MTIME_MS, false)?
                .visit_field::<u64>("size_bytes", Self::VT_SIZE_BYTES, false)?
                .finish();
            Ok(())
        }
    }
    pub struct FileEntryArgs<'a> {
        pub path: Option<flatbuffers::WIPOffset<&'a str>>,
        pub hash: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
        pub mtime_ms: u64,
        pub size_bytes: u64,
    }
    impl<'a> Default for FileEntryArgs<'a> {
        #[inline]
        fn default() -> Self {
            FileEntryArgs {
                path: None, // required field
                hash: None, // required field
                mtime_ms: 0,
                size_bytes: 0,
            }
        }
    }

    pub struct FileEntryBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> FileEntryBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_path(&mut self, path: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(FileEntry::VT_PATH, path);
        }
        #[inline]
        pub fn add_hash(&mut self, hash: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(FileEntry::VT_HASH, hash);
        }
        #[inline]
        pub fn add_mtime_ms(&mut self, mtime_ms: u64) {
            self.fbb_
                .push_slot::<u64>(FileEntry::VT_MTIME_MS, mtime_ms, 0);
        }
        #[inline]
        pub fn add_size_bytes(&mut self, size_bytes: u64) {
            self.fbb_
                .push_slot::<u64>(FileEntry::VT_SIZE_BYTES, size_bytes, 0);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> FileEntryBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            FileEntryBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<FileEntry<'a>> {
            let o = self.fbb_.end_table(self.start_);
            self.fbb_.required(o, FileEntry::VT_PATH, "path");
            self.fbb_.required(o, FileEntry::VT_HASH, "hash");
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for FileEntry<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("FileEntry");
            ds.field("path", &self.path());
            ds.field("hash", &self.hash());
            ds.field("mtime_ms", &self.mtime_ms());
            ds.field("size_bytes", &self.size_bytes());
            ds.finish()
        }
    }
    pub enum LeafChunkOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct LeafChunk<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for LeafChunk<'a> {
        type Inner = LeafChunk<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: flatbuffers::Table::new(buf, loc),
            }
        }
    }

    impl<'a> LeafChunk<'a> {
        pub const VT_VERSION: flatbuffers::VOffsetT = 4;
        pub const VT_ENTRIES: flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            LeafChunk { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args LeafChunkArgs<'args>,
        ) -> flatbuffers::WIPOffset<LeafChunk<'bldr>> {
            let mut builder = LeafChunkBuilder::new(_fbb);
            if let Some(x) = args.entries {
                builder.add_entries(x);
            }
            builder.add_version(args.version);
            builder.finish()
        }

        #[inline]
        pub fn version(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<u32>(LeafChunk::VT_VERSION, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn entries(
            &self,
        ) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<FileEntry<'a>>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<
                        flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<FileEntry>>,
                    >>(LeafChunk::VT_ENTRIES, None)
                    .unwrap()
            }
        }
    }

    impl flatbuffers::Verifiable for LeafChunk<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<u32>("version", Self::VT_VERSION, false)?
                .visit_field::<flatbuffers::ForwardsUOffset<
                    flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<FileEntry>>,
                >>("entries", Self::VT_ENTRIES, true)?
                .finish();
            Ok(())
        }
    }
    pub struct LeafChunkArgs<'a> {
        pub version: u32,
        pub entries: Option<
            flatbuffers::WIPOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<FileEntry<'a>>>,
            >,
        >,
    }
    impl<'a> Default for LeafChunkArgs<'a> {
        #[inline]
        fn default() -> Self {
            LeafChunkArgs {
                version: 0,
                entries: None, // required field
            }
        }
    }

    pub struct LeafChunkBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> LeafChunkBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_version(&mut self, version: u32) {
            self.fbb_
                .push_slot::<u32>(LeafChunk::VT_VERSION, version, 0);
        }
        #[inline]
        pub fn add_entries(
            &mut self,
            entries: flatbuffers::WIPOffset<
                flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<FileEntry<'b>>>,
            >,
        ) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(LeafChunk::VT_ENTRIES, entries);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> LeafChunkBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            LeafChunkBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<LeafChunk<'a>> {
            let o = self.fbb_.end_table(self.start_);
            self.fbb_.required(o, LeafChunk::VT_ENTRIES, "entries");
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for LeafChunk<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("LeafChunk");
            ds.field("version", &self.version());
            ds.field("entries", &self.entries());
            ds.finish()
        }
    }
    pub enum ChildRefOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct ChildRef<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for ChildRef<'a> {
        type Inner = ChildRef<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: flatbuffers::Table::new(buf, loc),
            }
        }
    }

    impl<'a> ChildRef<'a> {
        pub const VT_PREFIX: flatbuffers::VOffsetT = 4;
        pub const VT_HASH: flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            ChildRef { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args ChildRefArgs<'args>,
        ) -> flatbuffers::WIPOffset<ChildRef<'bldr>> {
            let mut builder = ChildRefBuilder::new(_fbb);
            if let Some(x) = args.hash {
                builder.add_hash(x);
            }
            if let Some(x) = args.prefix {
                builder.add_prefix(x);
            }
            builder.finish()
        }

        #[inline]
        pub fn prefix(&self) -> &'a str {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(ChildRef::VT_PREFIX, None)
                    .unwrap()
            }
        }
        #[inline]
        pub fn hash(&self) -> flatbuffers::Vector<'a, u8> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                        ChildRef::VT_HASH,
                        None,
                    )
                    .unwrap()
            }
        }
    }

    impl flatbuffers::Verifiable for ChildRef<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>("prefix", Self::VT_PREFIX, true)?
                .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                    "hash",
                    Self::VT_HASH,
                    true,
                )?
                .finish();
            Ok(())
        }
    }
    pub struct ChildRefArgs<'a> {
        pub prefix: Option<flatbuffers::WIPOffset<&'a str>>,
        pub hash: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    }
    impl<'a> Default for ChildRefArgs<'a> {
        #[inline]
        fn default() -> Self {
            ChildRefArgs {
                prefix: None, // required field
                hash: None,   // required field
            }
        }
    }

    pub struct ChildRefBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ChildRefBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_prefix(&mut self, prefix: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(ChildRef::VT_PREFIX, prefix);
        }
        #[inline]
        pub fn add_hash(&mut self, hash: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(ChildRef::VT_HASH, hash);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> ChildRefBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            ChildRefBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<ChildRef<'a>> {
            let o = self.fbb_.end_table(self.start_);
            self.fbb_.required(o, ChildRef::VT_PREFIX, "prefix");
            self.fbb_.required(o, ChildRef::VT_HASH, "hash");
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for ChildRef<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("ChildRef");
            ds.field("prefix", &self.prefix());
            ds.field("hash", &self.hash());
            ds.finish()
        }
    }
    pub enum InternalNodeOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct InternalNode<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for InternalNode<'a> {
        type Inner = InternalNode<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: flatbuffers::Table::new(buf, loc),
            }
        }
    }

    impl<'a> InternalNode<'a> {
        pub const VT_VERSION: flatbuffers::VOffsetT = 4;
        pub const VT_CHILDREN: flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            InternalNode { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args InternalNodeArgs<'args>,
        ) -> flatbuffers::WIPOffset<InternalNode<'bldr>> {
            let mut builder = InternalNodeBuilder::new(_fbb);
            if let Some(x) = args.children {
                builder.add_children(x);
            }
            builder.add_version(args.version);
            builder.finish()
        }

        #[inline]
        pub fn version(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<u32>(InternalNode::VT_VERSION, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn children(
            &self,
        ) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ChildRef<'a>>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<
                        flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ChildRef>>,
                    >>(InternalNode::VT_CHILDREN, None)
                    .unwrap()
            }
        }
    }

    impl flatbuffers::Verifiable for InternalNode<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<u32>("version", Self::VT_VERSION, false)?
                .visit_field::<flatbuffers::ForwardsUOffset<
                    flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<ChildRef>>,
                >>("children", Self::VT_CHILDREN, true)?
                .finish();
            Ok(())
        }
    }
    pub struct InternalNodeArgs<'a> {
        pub version: u32,
        pub children: Option<
            flatbuffers::WIPOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ChildRef<'a>>>,
            >,
        >,
    }
    impl<'a> Default for InternalNodeArgs<'a> {
        #[inline]
        fn default() -> Self {
            InternalNodeArgs {
                version: 0,
                children: None, // required field
            }
        }
    }

    pub struct InternalNodeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> InternalNodeBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_version(&mut self, version: u32) {
            self.fbb_
                .push_slot::<u32>(InternalNode::VT_VERSION, version, 0);
        }
        #[inline]
        pub fn add_children(
            &mut self,
            children: flatbuffers::WIPOffset<
                flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<ChildRef<'b>>>,
            >,
        ) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(InternalNode::VT_CHILDREN, children);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> InternalNodeBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            InternalNodeBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<InternalNode<'a>> {
            let o = self.fbb_.end_table(self.start_);
            self.fbb_.required(o, InternalNode::VT_CHILDREN, "children");
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for InternalNode<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("InternalNode");
            ds.field("version", &self.version());
            ds.field("children", &self.children());
            ds.finish()
        }
    }
    pub enum RootNodeOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct RootNode<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for RootNode<'a> {
        type Inner = RootNode<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: flatbuffers::Table::new(buf, loc),
            }
        }
    }

    impl<'a> RootNode<'a> {
        pub const VT_VERSION: flatbuffers::VOffsetT = 4;
        pub const VT_VAULT_ID: flatbuffers::VOffsetT = 6;
        pub const VT_CREATED_MS: flatbuffers::VOffsetT = 8;
        pub const VT_TOTAL_FILES: flatbuffers::VOffsetT = 10;
        pub const VT_CHILDREN: flatbuffers::VOffsetT = 12;
        pub const VT_ROOT_HASH: flatbuffers::VOffsetT = 14;
        pub const VT_PARENT_HASH: flatbuffers::VOffsetT = 16;
        pub const VT_DEVICE_ID: flatbuffers::VOffsetT = 18;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            RootNode { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args RootNodeArgs<'args>,
        ) -> flatbuffers::WIPOffset<RootNode<'bldr>> {
            let mut builder = RootNodeBuilder::new(_fbb);
            builder.add_total_files(args.total_files);
            builder.add_created_ms(args.created_ms);
            if let Some(x) = args.device_id {
                builder.add_device_id(x);
            }
            if let Some(x) = args.parent_hash {
                builder.add_parent_hash(x);
            }
            if let Some(x) = args.root_hash {
                builder.add_root_hash(x);
            }
            if let Some(x) = args.children {
                builder.add_children(x);
            }
            if let Some(x) = args.vault_id {
                builder.add_vault_id(x);
            }
            builder.add_version(args.version);
            builder.finish()
        }

        #[inline]
        pub fn version(&self) -> u32 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe { self._tab.get::<u32>(RootNode::VT_VERSION, Some(0)).unwrap() }
        }
        #[inline]
        pub fn vault_id(&self) -> &'a str {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(RootNode::VT_VAULT_ID, None)
                    .unwrap()
            }
        }
        #[inline]
        pub fn created_ms(&self) -> u64 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<u64>(RootNode::VT_CREATED_MS, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn total_files(&self) -> u64 {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<u64>(RootNode::VT_TOTAL_FILES, Some(0))
                    .unwrap()
            }
        }
        #[inline]
        pub fn children(
            &self,
        ) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ChildRef<'a>>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<
                        flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ChildRef>>,
                    >>(RootNode::VT_CHILDREN, None)
                    .unwrap()
            }
        }
        #[inline]
        pub fn root_hash(&self) -> Option<flatbuffers::Vector<'a, u8>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                        RootNode::VT_ROOT_HASH,
                        None,
                    )
            }
        }
        #[inline]
        pub fn parent_hash(&self) -> Option<flatbuffers::Vector<'a, u8>> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                        RootNode::VT_PARENT_HASH,
                        None,
                    )
            }
        }
        #[inline]
        pub fn device_id(&self) -> Option<&'a str> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<&str>>(RootNode::VT_DEVICE_ID, None)
            }
        }
    }

    impl flatbuffers::Verifiable for RootNode<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_field::<u32>("version", Self::VT_VERSION, false)?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                    "vault_id",
                    Self::VT_VAULT_ID,
                    true,
                )?
                .visit_field::<u64>("created_ms", Self::VT_CREATED_MS, false)?
                .visit_field::<u64>("total_files", Self::VT_TOTAL_FILES, false)?
                .visit_field::<flatbuffers::ForwardsUOffset<
                    flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<ChildRef>>,
                >>("children", Self::VT_CHILDREN, true)?
                .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                    "root_hash",
                    Self::VT_ROOT_HASH,
                    false,
                )?
                .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                    "parent_hash",
                    Self::VT_PARENT_HASH,
                    false,
                )?
                .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                    "device_id",
                    Self::VT_DEVICE_ID,
                    false,
                )?
                .finish();
            Ok(())
        }
    }
    pub struct RootNodeArgs<'a> {
        pub version: u32,
        pub vault_id: Option<flatbuffers::WIPOffset<&'a str>>,
        pub created_ms: u64,
        pub total_files: u64,
        pub children: Option<
            flatbuffers::WIPOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<ChildRef<'a>>>,
            >,
        >,
        pub root_hash: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
        pub parent_hash: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
        pub device_id: Option<flatbuffers::WIPOffset<&'a str>>,
    }
    impl<'a> Default for RootNodeArgs<'a> {
        #[inline]
        fn default() -> Self {
            RootNodeArgs {
                version: 0,
                vault_id: None, // required field
                created_ms: 0,
                total_files: 0,
                children: None, // required field
                root_hash: None,
                parent_hash: None,
                device_id: None,
            }
        }
    }

    pub struct RootNodeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> RootNodeBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_version(&mut self, version: u32) {
            self.fbb_.push_slot::<u32>(RootNode::VT_VERSION, version, 0);
        }
        #[inline]
        pub fn add_vault_id(&mut self, vault_id: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(RootNode::VT_VAULT_ID, vault_id);
        }
        #[inline]
        pub fn add_created_ms(&mut self, created_ms: u64) {
            self.fbb_
                .push_slot::<u64>(RootNode::VT_CREATED_MS, created_ms, 0);
        }
        #[inline]
        pub fn add_total_files(&mut self, total_files: u64) {
            self.fbb_
                .push_slot::<u64>(RootNode::VT_TOTAL_FILES, total_files, 0);
        }
        #[inline]
        pub fn add_children(
            &mut self,
            children: flatbuffers::WIPOffset<
                flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<ChildRef<'b>>>,
            >,
        ) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(RootNode::VT_CHILDREN, children);
        }
        #[inline]
        pub fn add_root_hash(
            &mut self,
            root_hash: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>,
        ) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(RootNode::VT_ROOT_HASH, root_hash);
        }
        #[inline]
        pub fn add_parent_hash(
            &mut self,
            parent_hash: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>,
        ) {
            self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
                RootNode::VT_PARENT_HASH,
                parent_hash,
            );
        }
        #[inline]
        pub fn add_device_id(&mut self, device_id: flatbuffers::WIPOffset<&'b str>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(RootNode::VT_DEVICE_ID, device_id);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> RootNodeBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            RootNodeBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<RootNode<'a>> {
            let o = self.fbb_.end_table(self.start_);
            self.fbb_.required(o, RootNode::VT_VAULT_ID, "vault_id");
            self.fbb_.required(o, RootNode::VT_CHILDREN, "children");
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for RootNode<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("RootNode");
            ds.field("version", &self.version());
            ds.field("vault_id", &self.vault_id());
            ds.field("created_ms", &self.created_ms());
            ds.field("total_files", &self.total_files());
            ds.field("children", &self.children());
            ds.field("root_hash", &self.root_hash());
            ds.field("parent_hash", &self.parent_hash());
            ds.field("device_id", &self.device_id());
            ds.finish()
        }
    }
    pub enum ChunkEnvelopeOffset {}
    #[derive(Copy, Clone, PartialEq)]

    pub struct ChunkEnvelope<'a> {
        pub _tab: flatbuffers::Table<'a>,
    }

    impl<'a> flatbuffers::Follow<'a> for ChunkEnvelope<'a> {
        type Inner = ChunkEnvelope<'a>;
        #[inline]
        unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
            Self {
                _tab: flatbuffers::Table::new(buf, loc),
            }
        }
    }

    impl<'a> ChunkEnvelope<'a> {
        pub const VT_NODE_TYPE: flatbuffers::VOffsetT = 4;
        pub const VT_NODE: flatbuffers::VOffsetT = 6;

        #[inline]
        pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
            ChunkEnvelope { _tab: table }
        }
        #[allow(unused_mut)]
        pub fn create<
            'bldr: 'args,
            'args: 'mut_bldr,
            'mut_bldr,
            A: flatbuffers::Allocator + 'bldr,
        >(
            _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
            args: &'args ChunkEnvelopeArgs,
        ) -> flatbuffers::WIPOffset<ChunkEnvelope<'bldr>> {
            let mut builder = ChunkEnvelopeBuilder::new(_fbb);
            if let Some(x) = args.node {
                builder.add_node(x);
            }
            builder.add_node_type(args.node_type);
            builder.finish()
        }

        #[inline]
        pub fn node_type(&self) -> NodeType {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<NodeType>(ChunkEnvelope::VT_NODE_TYPE, Some(NodeType::NONE))
                    .unwrap()
            }
        }
        #[inline]
        pub fn node(&self) -> flatbuffers::Table<'a> {
            // Safety:
            // Created from valid Table for this object
            // which contains a valid value in this slot
            unsafe {
                self._tab
                    .get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(
                        ChunkEnvelope::VT_NODE,
                        None,
                    )
                    .unwrap()
            }
        }
        #[inline]
        #[allow(non_snake_case)]
        pub fn node_as_leaf_chunk(&self) -> Option<LeafChunk<'a>> {
            if self.node_type() == NodeType::LeafChunk {
                let u = self.node();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                Some(unsafe { LeafChunk::init_from_table(u) })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn node_as_internal_node(&self) -> Option<InternalNode<'a>> {
            if self.node_type() == NodeType::InternalNode {
                let u = self.node();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                Some(unsafe { InternalNode::init_from_table(u) })
            } else {
                None
            }
        }

        #[inline]
        #[allow(non_snake_case)]
        pub fn node_as_root_node(&self) -> Option<RootNode<'a>> {
            if self.node_type() == NodeType::RootNode {
                let u = self.node();
                // Safety:
                // Created from a valid Table for this object
                // Which contains a valid union in this slot
                Some(unsafe { RootNode::init_from_table(u) })
            } else {
                None
            }
        }
    }

    impl flatbuffers::Verifiable for ChunkEnvelope<'_> {
        #[inline]
        fn run_verifier(
            v: &mut flatbuffers::Verifier,
            pos: usize,
        ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
            use self::flatbuffers::Verifiable;
            v.visit_table(pos)?
                .visit_union::<NodeType, _>(
                    "node_type",
                    Self::VT_NODE_TYPE,
                    "node",
                    Self::VT_NODE,
                    true,
                    |key, v, pos| match key {
                        NodeType::LeafChunk => v
                            .verify_union_variant::<flatbuffers::ForwardsUOffset<LeafChunk>>(
                                "NodeType::LeafChunk",
                                pos,
                            ),
                        NodeType::InternalNode => v
                            .verify_union_variant::<flatbuffers::ForwardsUOffset<InternalNode>>(
                                "NodeType::InternalNode",
                                pos,
                            ),
                        NodeType::RootNode => v
                            .verify_union_variant::<flatbuffers::ForwardsUOffset<RootNode>>(
                                "NodeType::RootNode",
                                pos,
                            ),
                        _ => Ok(()),
                    },
                )?
                .finish();
            Ok(())
        }
    }
    pub struct ChunkEnvelopeArgs {
        pub node_type: NodeType,
        pub node: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
    }
    impl<'a> Default for ChunkEnvelopeArgs {
        #[inline]
        fn default() -> Self {
            ChunkEnvelopeArgs {
                node_type: NodeType::NONE,
                node: None, // required field
            }
        }
    }

    pub struct ChunkEnvelopeBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
        fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
    }
    impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ChunkEnvelopeBuilder<'a, 'b, A> {
        #[inline]
        pub fn add_node_type(&mut self, node_type: NodeType) {
            self.fbb_
                .push_slot::<NodeType>(ChunkEnvelope::VT_NODE_TYPE, node_type, NodeType::NONE);
        }
        #[inline]
        pub fn add_node(&mut self, node: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
            self.fbb_
                .push_slot_always::<flatbuffers::WIPOffset<_>>(ChunkEnvelope::VT_NODE, node);
        }
        #[inline]
        pub fn new(
            _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        ) -> ChunkEnvelopeBuilder<'a, 'b, A> {
            let start = _fbb.start_table();
            ChunkEnvelopeBuilder {
                fbb_: _fbb,
                start_: start,
            }
        }
        #[inline]
        pub fn finish(self) -> flatbuffers::WIPOffset<ChunkEnvelope<'a>> {
            let o = self.fbb_.end_table(self.start_);
            self.fbb_.required(o, ChunkEnvelope::VT_NODE, "node");
            flatbuffers::WIPOffset::new(o.value())
        }
    }

    impl core::fmt::Debug for ChunkEnvelope<'_> {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            let mut ds = f.debug_struct("ChunkEnvelope");
            ds.field("node_type", &self.node_type());
            match self.node_type() {
                NodeType::LeafChunk => {
                    if let Some(x) = self.node_as_leaf_chunk() {
                        ds.field("node", &x)
                    } else {
                        ds.field(
                            "node",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                NodeType::InternalNode => {
                    if let Some(x) = self.node_as_internal_node() {
                        ds.field("node", &x)
                    } else {
                        ds.field(
                            "node",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                NodeType::RootNode => {
                    if let Some(x) = self.node_as_root_node() {
                        ds.field("node", &x)
                    } else {
                        ds.field(
                            "node",
                            &"InvalidFlatbuffer: Union discriminant does not match value.",
                        )
                    }
                }
                _ => {
                    let x: Option<()> = None;
                    ds.field("node", &x)
                }
            };
            ds.finish()
        }
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a `ChunkEnvelope`
    /// and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_chunk_envelope_unchecked`.
    pub fn root_as_chunk_envelope(
        buf: &[u8],
    ) -> Result<ChunkEnvelope, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::root::<ChunkEnvelope>(buf)
    }
    #[inline]
    /// Verifies that a buffer of bytes contains a size prefixed
    /// `ChunkEnvelope` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `size_prefixed_root_as_chunk_envelope_unchecked`.
    pub fn size_prefixed_root_as_chunk_envelope(
        buf: &[u8],
    ) -> Result<ChunkEnvelope, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::size_prefixed_root::<ChunkEnvelope>(buf)
    }
    #[inline]
    /// Verifies, with the given options, that a buffer of bytes
    /// contains a `ChunkEnvelope` and returns it.
    /// Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_chunk_envelope_unchecked`.
    pub fn root_as_chunk_envelope_with_opts<'b, 'o>(
        opts: &'o flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<ChunkEnvelope<'b>, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::root_with_opts::<ChunkEnvelope<'b>>(opts, buf)
    }
    #[inline]
    /// Verifies, with the given verifier options, that a buffer of
    /// bytes contains a size prefixed `ChunkEnvelope` and returns
    /// it. Note that verification is still experimental and may not
    /// catch every error, or be maximally performant. For the
    /// previous, unchecked, behavior use
    /// `root_as_chunk_envelope_unchecked`.
    pub fn size_prefixed_root_as_chunk_envelope_with_opts<'b, 'o>(
        opts: &'o flatbuffers::VerifierOptions,
        buf: &'b [u8],
    ) -> Result<ChunkEnvelope<'b>, flatbuffers::InvalidFlatbuffer> {
        flatbuffers::size_prefixed_root_with_opts::<ChunkEnvelope<'b>>(opts, buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a ChunkEnvelope and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid `ChunkEnvelope`.
    pub unsafe fn root_as_chunk_envelope_unchecked(buf: &[u8]) -> ChunkEnvelope {
        flatbuffers::root_unchecked::<ChunkEnvelope>(buf)
    }
    #[inline]
    /// Assumes, without verification, that a buffer of bytes contains a size prefixed ChunkEnvelope and returns it.
    /// # Safety
    /// Callers must trust the given bytes do indeed contain a valid size prefixed `ChunkEnvelope`.
    pub unsafe fn size_prefixed_root_as_chunk_envelope_unchecked(buf: &[u8]) -> ChunkEnvelope {
        flatbuffers::size_prefixed_root_unchecked::<ChunkEnvelope>(buf)
    }
    #[inline]
    pub fn finish_chunk_envelope_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
        fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        root: flatbuffers::WIPOffset<ChunkEnvelope<'a>>,
    ) {
        fbb.finish(root, None);
    }

    #[inline]
    pub fn finish_size_prefixed_chunk_envelope_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
        fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
        root: flatbuffers::WIPOffset<ChunkEnvelope<'a>>,
    ) {
        fbb.finish_size_prefixed(root, None);
    }
} // pub mod SyncChunk
